openapi: "3.0.3"
info:
  title: Test APP
  version: "1.0.1"
servers:
  - url: https://api.server.test/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Me:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
paths:
  /me:
    get:
      summary: Get current authenticated user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Authenticated user identity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Me"
        "401":
          description: Authentication failed/required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"